openapi: 3.0.0
info:
  title: Meme Generator API
  version: 1.0.0
  description: API for generating memes based on a given topic.
paths:
  /generate-meme:
    post:
      summary: Create a meme with caption texts based on the given topic.
      description: This endpoint allows users to generate a meme by providing a specific topic. The API will return the URL of the generated meme image.
      parameters:
        - name: meme_topic
          in: query
          required: true
          description: The topic for the meme, which will be used to generate the caption.
          schema:
            type: string
            example: "hackathon in Vilnius"
      responses:
        '200':
          description: Successfully generated meme image URL.
          content:
            application/json:
              schema:
                type: object
                properties:
                  image_url:
                    type: string
                    description: URL of the generated meme image.
                    example: "https://example.com/memes/hackathon-in-vilnius.jpg"
        '400':
          description: Bad request, invalid input.
        '500':
          description: Internal server error.